/**
 * Weapon configurations database
 */

import { WeaponType, WeaponConfig } from '@/types/game';

export const WEAPONS: Record<WeaponType, WeaponConfig> = {
  [WeaponType.BabyMissile]: {
    type: WeaponType.BabyMissile,
    name: 'Baby Missile',
    cost: 400,
    bundleSize: 10,
    blastRadius: 10,
    damage: 20,
    description: 'Basic attack, low cost',
  },
  [WeaponType.Missile]: {
    type: WeaponType.Missile,
    name: 'Missile',
    cost: 1875,
    bundleSize: 5,
    blastRadius: 20,
    damage: 40,
    description: 'Stronger basic attack',
  },
  [WeaponType.BabyNuke]: {
    type: WeaponType.BabyNuke,
    name: 'Baby Nuke',
    cost: 10000,
    bundleSize: 3,
    blastRadius: 40,
    damage: 80,
    description: 'Large area, high damage',
  },
  [WeaponType.Nuke]: {
    type: WeaponType.Nuke,
    name: 'Nuke',
    cost: 12000,
    bundleSize: 1,
    blastRadius: 75,
    damage: 150,
    description: 'Massive area, expensive',
  },
  [WeaponType.MIRV]: {
    type: WeaponType.MIRV,
    name: 'MIRV',
    cost: 10000,
    bundleSize: 3,
    blastRadius: 20,
    damage: 40,
    description: 'Splits into sub-munitions',
  },
  [WeaponType.DeathsHead]: {
    type: WeaponType.DeathsHead,
    name: "Death's Head",
    cost: 20000,
    bundleSize: 1,
    blastRadius: 35,
    damage: 70,
    description: 'Devastating, late-game',
  },
  [WeaponType.LeapFrog]: {
    type: WeaponType.LeapFrog,
    name: 'Leap Frog',
    cost: 10000,
    bundleSize: 2,
    blastRadius: 25,
    damage: 50,
    description: 'Bounces, hard to predict',
  },
  [WeaponType.FunkyBomb]: {
    type: WeaponType.FunkyBomb,
    name: 'Funky Bomb',
    cost: 7000,
    bundleSize: 2,
    blastRadius: 80,
    damage: 60,
    description: 'Unpredictable, wide coverage',
  },
  [WeaponType.Napalm]: {
    type: WeaponType.Napalm,
    name: 'Napalm',
    cost: 10000,
    bundleSize: 10,
    blastRadius: 15,
    damage: 30,
    description: 'Flows downhill, area denial',
  },
  [WeaponType.HotNapalm]: {
    type: WeaponType.HotNapalm,
    name: 'Hot Napalm',
    cost: 20000,
    bundleSize: 2,
    blastRadius: 25,
    damage: 50,
    description: 'More damage, larger spread',
  },
  [WeaponType.BabyRoller]: {
    type: WeaponType.BabyRoller,
    name: 'Baby Roller',
    cost: 5000,
    bundleSize: 10,
    blastRadius: 10,
    damage: 25,
    description: 'Rolls downhill, detonates on slope',
  },
  [WeaponType.Roller]: {
    type: WeaponType.Roller,
    name: 'Roller',
    cost: 6000,
    bundleSize: 5,
    blastRadius: 20,
    damage: 45,
    description: 'Rolls downhill, larger blast',
  },
  [WeaponType.HeavyRoller]: {
    type: WeaponType.HeavyRoller,
    name: 'Heavy Roller',
    cost: 6750,
    bundleSize: 2,
    blastRadius: 45,
    damage: 75,
    description: 'Rolls downhill, largest blast',
  },
  [WeaponType.RiotCharge]: {
    type: WeaponType.RiotCharge,
    name: 'Riot Charge',
    cost: 2000,
    bundleSize: 10,
    blastRadius: 36,
    damage: 5,
    description: 'Clears dirt, unburies tanks',
  },
  [WeaponType.RiotBlast]: {
    type: WeaponType.RiotBlast,
    name: 'Riot Blast',
    cost: 5000,
    bundleSize: 5,
    blastRadius: 60,
    damage: 8,
    description: 'Larger area, more effective',
  },
  [WeaponType.RiotBomb]: {
    type: WeaponType.RiotBomb,
    name: 'Riot Bomb',
    cost: 5000,
    bundleSize: 5,
    blastRadius: 30,
    damage: 5,
    description: 'Similar to Riot Charge',
  },
  [WeaponType.HeavyRiotBomb]: {
    type: WeaponType.HeavyRiotBomb,
    name: 'Heavy Riot Bomb',
    cost: 4750,
    bundleSize: 2,
    blastRadius: 45,
    damage: 8,
    description: 'Largest dirt clearing',
  },
  [WeaponType.BabyDigger]: {
    type: WeaponType.BabyDigger,
    name: 'Baby Digger',
    cost: 3000,
    bundleSize: 10,
    blastRadius: 5,
    damage: 10,
    description: 'Digs through terrain',
  },
  [WeaponType.Digger]: {
    type: WeaponType.Digger,
    name: 'Digger',
    cost: 2500,
    bundleSize: 5,
    blastRadius: 8,
    damage: 15,
    description: 'Digs larger tunnel',
  },
  [WeaponType.HeavyDigger]: {
    type: WeaponType.HeavyDigger,
    name: 'Heavy Digger',
    cost: 6750,
    bundleSize: 2,
    blastRadius: 12,
    damage: 20,
    description: 'Largest tunnel',
  },
  [WeaponType.BabySandhog]: {
    type: WeaponType.BabySandhog,
    name: 'Baby Sandhog',
    cost: 10000,
    bundleSize: 10,
    blastRadius: 6,
    damage: 12,
    description: 'Digs horizontally',
  },
  [WeaponType.Sandhog]: {
    type: WeaponType.Sandhog,
    name: 'Sandhog',
    cost: 16750,
    bundleSize: 5,
    blastRadius: 10,
    damage: 18,
    description: 'Digs larger horizontal tunnel',
  },
  [WeaponType.HeavySandhog]: {
    type: WeaponType.HeavySandhog,
    name: 'Heavy Sandhog',
    cost: 25000,
    bundleSize: 2,
    blastRadius: 15,
    damage: 25,
    description: 'Largest sandhog',
  },
  [WeaponType.DirtClod]: {
    type: WeaponType.DirtClod,
    name: 'Dirt Clod',
    cost: 5000,
    bundleSize: 10,
    blastRadius: 20,
    damage: 0,
    description: 'Covers tanks, creates obstacles',
  },
  [WeaponType.DirtBall]: {
    type: WeaponType.DirtBall,
    name: 'Dirt Ball',
    cost: 5000,
    bundleSize: 5,
    blastRadius: 35,
    damage: 0,
    description: 'Covers larger area',
  },
  [WeaponType.TonOfDirt]: {
    type: WeaponType.TonOfDirt,
    name: 'Ton of Dirt',
    cost: 6750,
    bundleSize: 2,
    blastRadius: 70,
    damage: 0,
    description: 'Largest dirt bomb',
  },
  [WeaponType.LiquidDirt]: {
    type: WeaponType.LiquidDirt,
    name: 'Liquid Dirt',
    cost: 5000,
    bundleSize: 10,
    blastRadius: 15,
    damage: 0,
    description: 'Flows like napalm',
  },
  [WeaponType.DirtCharge]: {
    type: WeaponType.DirtCharge,
    name: 'Dirt Charge',
    cost: 5000,
    bundleSize: 5,
    blastRadius: 25,
    damage: 0,
    description: 'Similar to Riot Charge, but adds',
  },
  [WeaponType.EarthDisrupter]: {
    type: WeaponType.EarthDisrupter,
    name: 'Earth Disrupter',
    cost: 5000,
    bundleSize: 10,
    blastRadius: 30,
    damage: 15,
    description: 'Alters terrain, unpredictable',
  },
  [WeaponType.PlasmaBlast]: {
    type: WeaponType.PlasmaBlast,
    name: 'Plasma Blast',
    cost: 9000,
    bundleSize: 5,
    blastRadius: 40,
    damage: 85,
    description: 'Variable blast, late-game',
  },
  [WeaponType.Laser]: {
    type: WeaponType.Laser,
    name: 'Laser',
    cost: 5000,
    bundleSize: 5,
    blastRadius: 2,
    damage: 100,
    description: 'Pierces terrain, instant hit',
  },
  [WeaponType.Tracer]: {
    type: WeaponType.Tracer,
    name: 'Tracer',
    cost: 10,
    bundleSize: 20,
    blastRadius: 0,
    damage: 0,
    description: 'Shows trajectory, no damage',
  },
  [WeaponType.SmokeTracer]: {
    type: WeaponType.SmokeTracer,
    name: 'Smoke Tracer',
    cost: 500,
    bundleSize: 10,
    blastRadius: 0,
    damage: 0,
    description: 'Trajectory, obscures vision',
  },
};

/**
 * Get weapon configuration by type
 */
export function getWeaponConfig(type: WeaponType): WeaponConfig {
  return WEAPONS[type];
}

/**
 * Get all weapons sorted by cost
 */
export function getAllWeapons(): WeaponConfig[] {
  return Object.values(WEAPONS).sort((a, b) => a.cost - b.cost);
}
